// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

// USERS
export const RESET_USERS = 'RESET_USERS';
export const GET_ME = 'GET_ME';
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const UPDATE_ME = 'UPDATE_ME';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const BLOCK_USER = 'BLOCK_USER';
export const UNBLOCK_USER = 'UNBLOCK_USER';
export const USER_ERROR = 'USER_ERROR';

// CATEGORIES
export const RESET_CATEGORIES = 'RESET_CATEGORIES';
export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY_POSTS = 'GET_CATEGORY_POSTS';
export const SET_GENRE = 'SET_GENRE';
export const INCREMENT_CATEGORIES_PAGE = 'INCREMENT_CATEGORIES_PAGE';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';

// POSTS
export const RESET_POSTS = 'RESET_POSTS';
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const GET_POSTS = 'GET_POSTS';
export const GET_POST = 'GET_POST';
export const CREATE_POST = 'CREATE_POST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';
export const UNLIKE_POST = 'UNLIKE_POST';
export const SAVE_POST = 'SAVE_POST';
export const UNSAVE_POST = 'UNSAVE_POST';
export const INCREMENT_POSTS_PAGE = 'INCREMENT_POSTS_PAGE';
export const RESET_POSTS_PAGE = 'RESET_POSTS_PAGE';
export const SET_PAGE_LIMIT = 'SET_PAGE_LIMIT';
export const POST_ERROR = 'POST_ERROR';

// COMMENTS
export const RESET_COMMENTS = 'RESET_COMMENTS';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENT = 'GET_COMMENT';
export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const LIKE_COMMENT = 'LIKE_COMMENT';
export const UNLIKE_COMMENT = 'UNLIKE_COMMENT';
export const INCREMENT_COMMENTS_PAGE = 'INCREMENT_COMMENTS_PAGE';
export const RESET_COMMENTS_PAGE = 'RESET_COMMENTS_PAGE';
export const SET_COMMENT_LIMIT = 'SET_COMMENT_LIMIT';
export const COMMENT_ERROR = 'COMMENT_ERROR';

// NOTIFICATIONS
export const RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const INCREMENT_NOTIFICATIONS_PAGE = 'INCREMENT_NOTIFICATIONS_PAGE';
export const RESET_NOTIFICATIONS_PAGE = 'RESET_NOTIFICATIONS_PAGE';
export const SET_NOTIFICATION_LIMIT = 'SET_NOTIFICATION_LIMIT';
export const NOTIFICATION_ERROR = 'NOTIFICATION_ERROR';

// REPORTS
export const RESET_REPORTS = 'RESET_REPORTS';
export const FETCH_REPORTS_START = 'FETCH_REPORTS_START';
export const GET_REPORTS = 'GET_REPORTS';
export const GET_REPORT = 'GET_REPORT';
export const CREATE_REPORT = 'CREATE_REPORT';
export const UPDATE_REPORT = 'UPDATE_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const INCREMENT_REPORTS_PAGE = 'INCREMENT_REPORTS_PAGE';
export const RESET_REPORTS_PAGE = 'RESET_REPORTS_PAGE';
export const SET_REPORT_LIMIT = 'SET_REPORT_LIMIT';
export const REPORT_ERROR = 'REPORT_ERROR';
